export interface Ingredient {
  id: string
  name: string
  category: string
  // Nutritional values per 100g
  calories: number
  protein: number // grams
  carbs: number // grams
  fat: number // grams
  fiber: number // grams
  sugar: number // grams
  sodium: number // mg
  // Additional properties
  isOrganic?: boolean
  allergens?: string[]
}

export const INGREDIENTS_DB: Record<string, Ingredient> = {
  // Proteins
  "chicken-breast": {
    id: "chicken-breast",
    name: "Chicken Breast (skinless)",
    category: "protein",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    sugar: 0,
    sodium: 74,
    allergens: [],
  },
  "salmon-fillet": {
    id: "salmon-fillet",
    name: "Salmon Fillet",
    category: "protein",
    calories: 208,
    protein: 25.4,
    carbs: 0,
    fat: 12.4,
    fiber: 0,
    sugar: 0,
    sodium: 59,
    allergens: ["fish"],
  },
  "turkey-ground-lean": {
    id: "turkey-ground-lean",
    name: "Ground Turkey (lean)",
    category: "protein",
    calories: 189,
    protein: 27.4,
    carbs: 0,
    fat: 8.3,
    fiber: 0,
    sugar: 0,
    sodium: 98,
    allergens: [],
  },
  "beef-lean": {
    id: "beef-lean",
    name: "Lean Beef",
    category: "protein",
    calories: 250,
    protein: 26,
    carbs: 0,
    fat: 15,
    fiber: 0,
    sugar: 0,
    sodium: 72,
    allergens: [],
  },
  "tuna-fresh": {
    id: "tuna-fresh",
    name: "Fresh Tuna",
    category: "protein",
    calories: 144,
    protein: 30,
    carbs: 0,
    fat: 0.6,
    fiber: 0,
    sugar: 0,
    sodium: 50,
    allergens: ["fish"],
  },
  "eggs-whole": {
    id: "eggs-whole",
    name: "Whole Eggs",
    category: "protein",
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    fiber: 0,
    sugar: 1.1,
    sodium: 124,
    allergens: ["eggs"],
  },
  "egg-whites": {
    id: "egg-whites",
    name: "Egg Whites",
    category: "protein",
    calories: 52,
    protein: 11,
    carbs: 0.7,
    fat: 0.2,
    fiber: 0,
    sugar: 0.7,
    sodium: 166,
    allergens: ["eggs"],
  },
  "tofu-firm": {
    id: "tofu-firm",
    name: "Firm Tofu",
    category: "protein",
    calories: 144,
    protein: 17.3,
    carbs: 2.8,
    fat: 8.7,
    fiber: 2.3,
    sugar: 0.6,
    sodium: 14,
    allergens: ["soy"],
  },

  // Carbohydrates
  "quinoa-cooked": {
    id: "quinoa-cooked",
    name: "Quinoa (cooked)",
    category: "carbs",
    calories: 120,
    protein: 4.4,
    carbs: 22,
    fat: 1.9,
    fiber: 2.8,
    sugar: 0.9,
    sodium: 7,
    allergens: [],
  },
  "brown-rice-cooked": {
    id: "brown-rice-cooked",
    name: "Brown Rice (cooked)",
    category: "carbs",
    calories: 112,
    protein: 2.6,
    carbs: 23,
    fat: 0.9,
    fiber: 1.8,
    sugar: 0.4,
    sodium: 5,
    allergens: [],
  },
  "sweet-potato": {
    id: "sweet-potato",
    name: "Sweet Potato",
    category: "carbs",
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
    fiber: 3,
    sugar: 4.2,
    sodium: 54,
    allergens: [],
  },
  "oats-rolled": {
    id: "oats-rolled",
    name: "Rolled Oats",
    category: "carbs",
    calories: 389,
    protein: 16.9,
    carbs: 66.3,
    fat: 6.9,
    fiber: 10.6,
    sugar: 0.99,
    sodium: 2,
    allergens: ["gluten"],
  },
  "whole-wheat-tortilla": {
    id: "whole-wheat-tortilla",
    name: "Whole Wheat Tortilla",
    category: "carbs",
    calories: 300,
    protein: 9,
    carbs: 51,
    fat: 8,
    fiber: 4,
    sugar: 2,
    sodium: 600,
    allergens: ["gluten"],
  },

  // Vegetables
  broccoli: {
    id: "broccoli",
    name: "Broccoli",
    category: "vegetables",
    calories: 34,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
    fiber: 2.6,
    sugar: 1.5,
    sodium: 33,
    allergens: [],
  },
  spinach: {
    id: "spinach",
    name: "Spinach",
    category: "vegetables",
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    sugar: 0.4,
    sodium: 79,
    allergens: [],
  },
  "bell-peppers": {
    id: "bell-peppers",
    name: "Bell Peppers",
    category: "vegetables",
    calories: 31,
    protein: 1,
    carbs: 7,
    fat: 0.3,
    fiber: 2.5,
    sugar: 4.2,
    sodium: 4,
    allergens: [],
  },
  carrots: {
    id: "carrots",
    name: "Carrots",
    category: "vegetables",
    calories: 41,
    protein: 0.9,
    carbs: 10,
    fat: 0.2,
    fiber: 2.8,
    sugar: 4.7,
    sodium: 69,
    allergens: [],
  },
  zucchini: {
    id: "zucchini",
    name: "Zucchini",
    category: "vegetables",
    calories: 17,
    protein: 1.2,
    carbs: 3.1,
    fat: 0.3,
    fiber: 1,
    sugar: 2.5,
    sodium: 8,
    allergens: [],
  },
  asparagus: {
    id: "asparagus",
    name: "Asparagus",
    category: "vegetables",
    calories: 20,
    protein: 2.2,
    carbs: 3.9,
    fat: 0.1,
    fiber: 2.1,
    sugar: 1.9,
    sodium: 2,
    allergens: [],
  },
  mushrooms: {
    id: "mushrooms",
    name: "Mushrooms",
    category: "vegetables",
    calories: 22,
    protein: 3.1,
    carbs: 3.3,
    fat: 0.3,
    fiber: 1,
    sugar: 2,
    sodium: 5,
    allergens: [],
  },

  // Healthy Fats
  avocado: {
    id: "avocado",
    name: "Avocado",
    category: "fats",
    calories: 160,
    protein: 2,
    carbs: 9,
    fat: 15,
    fiber: 7,
    sugar: 0.7,
    sodium: 7,
    allergens: [],
  },
  "olive-oil": {
    id: "olive-oil",
    name: "Extra Virgin Olive Oil",
    category: "fats",
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    sugar: 0,
    sodium: 2,
    allergens: [],
  },
  almonds: {
    id: "almonds",
    name: "Almonds",
    category: "fats",
    calories: 579,
    protein: 21.2,
    carbs: 21.6,
    fat: 49.9,
    fiber: 12.5,
    sugar: 4.4,
    sodium: 1,
    allergens: ["nuts"],
  },
  walnuts: {
    id: "walnuts",
    name: "Walnuts",
    category: "fats",
    calories: 654,
    protein: 15.2,
    carbs: 13.7,
    fat: 65.2,
    fiber: 6.7,
    sugar: 2.6,
    sodium: 2,
    allergens: ["nuts"],
  },

  // Dairy
  "greek-yogurt": {
    id: "greek-yogurt",
    name: "Greek Yogurt (plain)",
    category: "dairy",
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    fiber: 0,
    sugar: 3.6,
    sodium: 36,
    allergens: ["dairy"],
  },
  "cottage-cheese": {
    id: "cottage-cheese",
    name: "Cottage Cheese (low-fat)",
    category: "dairy",
    calories: 72,
    protein: 12.4,
    carbs: 4.3,
    fat: 0.4,
    fiber: 0,
    sugar: 4.1,
    sodium: 405,
    allergens: ["dairy"],
  },

  // Fruits
  blueberries: {
    id: "blueberries",
    name: "Blueberries",
    category: "fruits",
    calories: 57,
    protein: 0.7,
    carbs: 14.5,
    fat: 0.3,
    fiber: 2.4,
    sugar: 10,
    sodium: 1,
    allergens: [],
  },
  strawberries: {
    id: "strawberries",
    name: "Strawberries",
    category: "fruits",
    calories: 32,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
    fiber: 2,
    sugar: 4.9,
    sodium: 1,
    allergens: [],
  },
  banana: {
    id: "banana",
    name: "Banana",
    category: "fruits",
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    fiber: 2.6,
    sugar: 12.2,
    sodium: 1,
    allergens: [],
  },
}

// Helper function to get ingredient by ID
export function getIngredient(id: string): Ingredient | null {
  return INGREDIENTS_DB[id] || null
}

// Helper function to search ingredients by name or category
export function searchIngredients(query: string): Ingredient[] {
  const lowercaseQuery = query.toLowerCase()
  return Object.values(INGREDIENTS_DB).filter(
    (ingredient) =>
      ingredient.name.toLowerCase().includes(lowercaseQuery) ||
      ingredient.category.toLowerCase().includes(lowercaseQuery),
  )
}
